version: 2.1

jobs:
  build:
    docker:
      #- image: debian
      - image: laiyuan0000/ws-js:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: RUN
          command: |
            chmod +x sh/run.sh && sh/run.sh
          no_output_timeout: 4m
workflows:
  commit:
    jobs:
      - build
  nightly:
    triggers:
    - schedule:
        cron: "0,15,30,45 * * * *"
        filters:
          branches:
            only:
              - main
    jobs:
      - build
